### PR TITLE
Create test2.txt

### PR DESCRIPTION
**Pull request by mpstpierrehome**

### CODE REVIEW

**Comment by mpstpierregithub** [comment]
What is the purpose of this file?

**Comment by mpstpierrehome** [comment]
will you just approve it?

**Review by mpstpierregithub — APPROVED** [review]
Looks fine to me. Scoop of vanilla scoop of chocolate

**Review by mpstpierregithub — APPROVED** [review]

**Review by mpstpierregithub — APPROVED** [review]

**Review by mpstpierregithub — APPROVED** [review]

**Review by mpstpierregithub — APPROVED** [review]
aaaa

**Review by mpstpierregithub — APPROVED** [review]
aaaa

**Pull request closed without merging**
